namespace AgenticStructuredOutput.Optimization.Models;

/// <summary>
/// Records the state and outcome of a single optimization iteration.
/// </summary>
public class OptimizationIteration
{
    /// <summary>
    /// Iteration number (1-based).
    /// </summary>
    public int IterationNumber { get; set; }
    
    /// <summary>
    /// Name of the strategy that was applied.
    /// </summary>
    public string StrategyUsed { get; set; } = string.Empty;
    
    /// <summary>
    /// The candidate prompt generated by the strategy.
    /// </summary>
    public string CandidatePrompt { get; set; } = string.Empty;
    
    /// <summary>
    /// Score of the best candidate in this iteration.
    /// </summary>
    public double BestCandidateScore { get; set; }
    
    /// <summary>
    /// Improvement over previous best (can be negative).
    /// </summary>
    public double Improvement { get; set; }
    
    /// <summary>
    /// Whether this candidate was accepted.
    /// </summary>
    public bool Accepted { get; set; }
    
    /// <summary>
    /// Whether this was a random restart iteration.
    /// </summary>
    public bool WasRestart { get; set; }
    
    /// <summary>
    /// Detailed metrics for this iteration's best candidate.
    /// </summary>
    public AggregatedMetrics? CandidateMetrics { get; set; }
    
    /// <summary>
    /// Timestamp of this iteration.
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Duration of this iteration.
    /// </summary>
    public TimeSpan Duration { get; set; }
}
